{{- range $clusterName, $cluster := .Values.kafkaClusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-kafka-cluster-{{ $clusterName }}
  labels:
    cloudflow.lightbend.com/kafka-cluster-name: {{ $clusterName }}
    {{- include "cloudflow.labels" $ | indent 4 }}
type: Opaque
stringData:
  secret.conf: |
    bootstrap.servers = {{ quote $cluster.bootstrapServers }}
    partitions = {{ $cluster.partitions }}
    replicas = {{ $cluster.replicas }}
    connection-config = {
      {{- range $key, $val := $cluster.connectionConfig }}
      {{ $key }} = {{ quote $val }}
      {{- end }}
    }
    producer-config = {
      {{- range $key, $val := $cluster.producerConfig }}
      {{ $key }} = {{ quote $val }}
      {{- end }}
    }
    consumer-config = {
      {{- range $key, $val := $cluster.consumerConfig }}
      {{ $key }} = {{ quote $val }}
      {{- end }}
    }
{{- end }}
